""" This module holds a dictionary for grouping serach terms."""

MODULE_FILTER_CATEGORIES: dict[str, list[str]] = {
	"AI": [
        # English
        "AI",
        "artificial intelligence",
		"classification",
        "computational intelligence",
        "computer vision",
        "data mining",
        "deep learning",
        "generative model",
		"intelligence",
        "intelligent system",
        "knowledge management",
        "knowledge representation",
        "large language model",
        "machine learning",
        "MLOps",
        "natural language processing",
        "neural network",
        "recommender",
        "reinforcement learning",
        "swarm intelligence",
        # German
		"intelligenz",
        "intelligente systeme",
        "KI",
		"klassifikation",
        "künstliche intelligenz",
        "maschinelles lernen",
		"neuronale netze",
        "wissensmanagement",
        "wissensrepräsentation",
		"schwarm intelligenz"
    ],
	"ComputerGame": [
        # English
		"3D",
        "animation",
		"AR",
        "augmented reality",
        "computer graphic",
        "computational intelligence in game",
        "digital games",
        "game",
        "game design",
        "game development",
		"graphic",
        "interaction",
        "interactive system",
		"MR",
		"real-time",
        "rendering",
        "simulation",
        "virtual reality",
        "visualization",
		"VR",
		"XR",
        # German
        "computergraphik",
        "digitale spiele",
		"echtzeit",
        "erweiterte realität",
        "gemischte realität",
		"grafik",
		"interaktion",
        "interaktive systeme",
        "spiel",
        "virtuelle realität",
	],
	"SystemsEngineering": [
        # English
        "clean code",
        "compiler",
        "data analysis",
        "data engineering",
        "data management",
        "data mining",
        "data science",
        "data warehouse",
        "database",
        "distributed data",
        "evaluation",
		"git",
        "learning workflow",
        "modeling",
        "NoSQL",
        "programming paradigms",
        "scrum",
        "software development",
        "software engineering",
        "software product lines",
        "software project",
        "specification",
        "SQL",
        "statistical analysis",
        "text analysis",
        "testing",
        "transaction",
        # German
        "compilerbau",
        "datenanalyse",
        "datenbank",
        "datenbanken",
        "datenmanagement",
        "modellierung",
        "programmierparadigmen",
        "softwareentwicklung",
        "softwareprojekt",
        "spezifikationstechnik",
        "statistische analyse",
		"testen",
    ],
	"ScientificComputing": [
        # English
		"differential",
        "differential equations",
        "discrete-event simulation",
        "distributed computing",
        "efficient programming",
        "high performance computing",
        "HPC",
        "mainframe",
        "markov chains",
        "modeling",
        "modelling",
        "numerical integration",
        "numerical simulation",
        "ordinary differential equations",
        "parallel",
        "parallel computing",
        "parallel programming",
        "petri nets",
        "scientific",
        "scientific computing",
        "simulation",
        "stochastic",
        "stochastic models",
        "storage systems",
        # German
        "diskrete ereignissimulation",
        "effiziente programmierung",
        "markov-ketten",
        "modellierung",
        "numerische simulation",
        "parallele programmierung",
        "stochastische modelle",
        "wissenschaftlich",
        "wissenschaftliches rechnen",
	],
}
